### ISSUE TITLE
--list_algorithms causes AttributeError: module 'hashlib' has no attribute 'algorithms'

### ISSUE THREAD

**Issue by DannyBen** [jjmontesl/codenamize#2]
```shell
$ codenamize --list_algorithms
Traceback (most recent call last):
  File "/usr/local/bin/codenamize", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/codenamize/codenamize.py", line 304, in main
    for a in hashlib.algorithms:
AttributeError: module 'hashlib' has no attribute 'algorithms'

$ python3 --version
Python 3.5.2
```

**Comment by jjmontesl** [comment]
Fixed in 1.2.3, already available via pip (commit 65f1e34).
